### PR TITLE
add color to prompts

### PR DESCRIPTION
**Pull request by HedvigS**

### CODE REVIEW

**Comment by johenglisch** [comment]
I'm confused by this PR:

 * That line with the coloured printing is already in `master`: https://github.com/grambank/pygrambank/blob/8d405ec10dc9f043083f346aa97263c65ad62ede/src/pygrambank/srctok.py#L138
 * On your fork, the last commit before the `.gitignore` commit is 7 months old.

I'm scared of what happens if I try to merge things like that.  Could you try and merge the upstream `master` branch into your fork, so the two repos are on the same page?

**Comment by xrotwang** [comment]
AFAICT, both changes have already be commited to master before: https://github.com/grambank/pygrambank/commit/e1bfba7cb6cb859ce592fee6dc6ea34b432c118f

**Comment by johenglisch** [comment]
Oh, right – I forgot to double-check the `.gitignore`.  So, yeah, the `.DS_Store` line is in there.

So, I guess I'll just close this.

**Comment by HedvigS** [comment]
Yes I saw this branch still hanging around so I thought it hadn't been merged in. My bad.

**Pull request closed without merging**
