### PR TITLE
remove dc:conformsTo null for families

### PR DESCRIPTION
**Pull request by HedvigS**
I may have gotten this wrong, but this to me seems to be the change necessary to make the non-cldf contributors and families table both be the same in terms of dcconformsTo (i.e. it's not listed as opposed to being NULL).

### CODE REVIEW

**Review by xrotwang — APPROVED** [review]

**Comment by HedvigS** [comment]
There was a conflict due to some line breaks in cldf.py by someone else. I believe I resolved it correctly.

**Comment by xrotwang** [comment]
I already folded this change into `master`. So we can close this.

**Comment by HedvigS** [comment]
Oh? Okay. To me it looks like  e7b3e58 is approved by not merged in.

**Comment by HedvigS** [comment]
Ah.. 3fcdf52ec369c19e379d901391a0b42e6fd347d5 did it.

**Pull request closed without merging**
